#!/usr/bin/env bash
# A Bash script that creates the file /var/run/myscript.pid containing its PID

function  remove {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

until false
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I hate the kill command" && remove' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'remove' SIGQUIT
done
