#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10

q=1

while [ $q -le 10 ]
do
    if [ $q -eq 4 ];
    then
	echo "bad luck"
    elif [ $q -eq 8 ];
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( q++ ))
done
