#!/usr/bin/env bash
#Bash script that displays nō 1-10

w=1
while [ $w -le 20 ]
do
  echo "$w"
  case $w in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( w++ ))
done
