#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=hr; hr=0
while [ $hr -le 12 ]
do
  echo "Hour: $hr"
  minute=min; min=0
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( hrs++ ))
done
